Add denomination float
ElrondNetwork/api.elrond.com pull request #101
Opened 2021-08-29 13:33 UTC by mihaieremia

Added a new denominationFloat method which is using the old format function from express-api.

2021-08-29 13:51 UTC, tanghel requested changes
- please re-open this PR against the development branch
- also, please use the Balance.toDenominated function of the erdjs framework for the computation
- last but not least, would be great to have some unit tests in the tests/helpers.spec.ts for this

Thank you! 💪

2021-09-06 09:05 UTC, tanghel submitted a review, later dismissed

2021-09-06 09:06 UTC, AlexandruPislariu submitted a review, later dismissed

2021-09-10 07:31 UTC, AlexandruPislariu commented on src/endpoints/network/entities/networkConfig.ts
> +export class NetworkConfig {
Please change filename to `'network.config.ts'` to keep same structure.
Thank you!

2021-09-13 07:37 UTC, AlexandruPislariu approved these changes

2021-09-13 13:26 UTC, tanghel approved these changes

2021-09-13 13:26 UTC, merged