Add account history
ElrondNetwork/api.elrond.com pull request #463
Opened 2022-02-15 14:17 UTC by CristianFodor

## Type
- [ ] Bug
- [x] Feature  
- [ ] Performance improvement

## Problem setting
Extracting data regarding account balance history and account token balance history
  
## Proposed Changes
- 
- 
- 

## How to test
devnet-api.elrond.com/accounts/:address/history
devnet-api.elrond.com/accounts/:address/history/:tokenIdentifier

2022-02-16 07:38 UTC, AlexandruPislariu commented
Hello Cristian! Thank you for your contribution.
Can you please solve the conflicts in your local fork?

2022-02-16 09:50 UTC, CristianFodor commented
> Hello Cristian! Thank you for your contribution. Can you please solve the conflicts in your local fork?

Hi Alexandru! I did it, please have a look again.

2022-02-17 08:14 UTC, AlexandruPislariu reviewed
Awesome integration! Thank you for contributing to our public API.
I have just a few small comments.

2022-02-17 08:21 UTC, AlexandruPislariu requested changes

2022-02-17 08:21 UTC, AlexandruPislariu commented on src/endpoints/accounts/account.service.ts
> +    const shouldQueries: AbstractQuery[] = [];
Can be removed since it isn't used

2022-02-17 08:21 UTC, AlexandruPislariu commented on src/endpoints/accounts/account.service.ts
> +    if(!tokenIdentifier){
The tokenIdentifier can't be undefined or null so this check will have no effect.

2022-02-17 08:21 UTC, AlexandruPislariu commented on src/endpoints/accounts/account.controller.ts
> +    type: SmartContractResult,
Here the type should be AccountHistory[]

2022-02-17 08:21 UTC, AlexandruPislariu commented on src/endpoints/accounts/account.controller.ts
> +    type: SmartContractResult,
Also, here the type should be AccountEsdtHistory[]

2022-02-17 08:21 UTC, AlexandruPislariu commented on src/endpoints/accounts/entities/account.esdt.history.ts
> +export class AccountEsdtHistory {
I think this class should be inherited from AccountHistory and just add the token property in addition.

2022-02-17 13:56 UTC, AlexandruPislariu approved these changes

2022-02-21 10:02 UTC, tanghel approved these changes

2022-02-21 10:03 UTC, merged