Dev merge
ElrondNetwork/api.elrond.com pull request #49
Opened 2021-08-03 07:17 UTC by tanghel

2021-08-03 07:20 UTC, AlexandruPislariu submitted a review, later dismissed

2021-08-03 08:14 UTC, AlexandruPislariu approved these changes

2021-08-03 08:25 UTC, ccorcoveanu approved these changes

2021-08-04 10:41 UTC, AlexandruPislariu approved these changes

2021-08-09 09:30 UTC, ccorcoveanu requested changes
A general fix that needs to be done: either every person working on this project needs to have the IDE respect and add warnings/errors for the `eslint` file. If it's too restrictive, we could have exceptions. Right now every file I open is red on almost every line (for formatting, functions without return types, etc)

2021-08-09 11:19 UTC, tanghel commented on config/config.mainnet.yaml
> +  - 1952123
Hi! I received these numbers in an excel file, if they need to be changed we can easily update these values

2021-08-09 11:23 UTC, tanghel commented on src/helpers/helpers.ts
> +Date.prototype.isToday = function(): boolean {
from where I come from (.NET), extension methods are part of the expected extension of the system and it's probably the way I got used to it. besides extending Date & Strings, there are also helpful extension methods on arrays that make it easier to work with them. Maybe this is a bit more philosophical and we can clarify this "off-chain" :)

2021-08-10 14:48 UTC, ccorcoveanu approved these changes

2021-08-10 14:50 UTC, AlexandruPislariu approved these changes

2021-08-10 15:00 UTC, merged