add transfers query
ElrondNetwork/api.elrond.com pull request #851
Opened 2022-10-17 13:06 UTC by CatalinFaurPaul

## Description of the reasoning behind the pull request (what feature was missing / how the problem was manifesting itself / what was the motive behind the refactoring)
-  Add Transfers Query Graphql

  
## Proposed Changes
- Create transfers graphql query - transfers & transfersCount

## How to test
-  `graphql: true`
-  `indexer-v3: true`
Run query:
```
query{
  transfers(input:{
  }){
    txHash
    gasLimit
    gasPrice
    gasUsed
    miniBlockHash
    nonce
    receiverAddress
    receiverShard
    round
    senderAddress
    senderShard
    signature
    status
    value
    fee
    timestamp
    data
    type
    originalTxHash
  }
}
```

2022-10-18 06:19 UTC, AlexandruPislariu requested changes

2022-10-18 06:19 UTC, AlexandruPislariu commented on src/endpoints/transactions/entities/transaction.ts
> +  @Field(() => String, { description: "Original tx hasg for the given transaction.", nullable: true })
typo here 'hasg'

2022-10-18 06:19 UTC, AlexandruPislariu commented on src/graphql/entities/transfers/transfers.input.ts
> +@InputType({ description: "Input to retreive the given transfers count for." })
typo here 'retreive'

2022-10-18 08:51 UTC, CatalinFaurPaul commented on src/graphql/entities/transfers/transfers.input.ts
> +@InputType({ description: "Input to retreive the given transfers count for." })
Fixed

2022-10-18 08:52 UTC, CatalinFaurPaul commented on src/endpoints/transactions/entities/transaction.ts
> +  @Field(() => String, { description: "Original tx hasg for the given transaction.", nullable: true })
Fixed

2022-10-19 09:46 UTC, tanghel approved these changes

2022-10-19 09:47 UTC, merged