add fees collector address labelling
ElrondNetwork/api.elrond.com pull request #894
Opened 2022-11-15 17:26 UTC by CatalinFaurPaul

## Description of the reasoning behind the pull request (what feature was missing / how the problem was manifesting itself / what was the motive behind the refactoring)
-  there was no labels for the fees collector address
  
## Proposed Changes
- add label to fees collector address

## How to test
- accounts/erd1qqqqqqqqqqqqqpgqur83hqn9j4y6v93m09nn2q0yazuhk2rvpr9sarz5yj -> `assets` attribute should be defined

2022-11-15 20:47 UTC, dragos-rebegea approved these changes

2022-11-15 20:50 UTC, dragos-rebegea commented
I think you can even have a much bigger ttl; there is only one address it doesn`t change

2022-11-15 20:55 UTC, dragos-rebegea requested changes

2022-11-15 20:55 UTC, dragos-rebegea commented on src/common/assets/assets.service.ts
> +        name: `Maiar Exchange: Fees Collector Address`,
```suggestion
        name: `Maiar Exchange: Fees Collector Contract`,
```

2022-11-15 20:58 UTC, CatalinFaurPaul commented on src/common/assets/assets.service.ts
> +        name: `Maiar Exchange: Fees Collector Address`,
Changed

2022-11-15 21:06 UTC, dragos-rebegea approved these changes

2022-12-08 17:31 UTC, tanghel approved these changes

2022-12-08 17:31 UTC, merged